# Section 1:  NumPy Solutions

#### Import the library with alias np

In [19]:
import numpy as np

####  1. Create an array of  8 eights

In [20]:
np.ones(8)*8

array([8., 8., 8., 8., 8., 8., 8., 8.])

#### 2. Create an array of the integers from 10 to 50

In [21]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### 3. Create a 3x3 matrix with values ranging from 22 to 30

In [22]:
np.arange(22,31).reshape(3,3)

array([[22, 23, 24],
       [25, 26, 27],
       [28, 29, 30]])

## Indexing
Use below Array 'arr' for Questions below. 

Use Indexing to get the answer

In [23]:
arr = np.arange(26,51).reshape(5,5)
arr

array([[26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50]])

#### 4. Use indexing on arr to get below output

       [[37, 38, 39, 40],
       [42, 43, 44, 45],
       [47, 48, 49, 50]]

In [24]:
arr[2:,1:]

array([[37, 38, 39, 40],
       [42, 43, 44, 45],
       [47, 48, 49, 50]])

#### 5. Use indexing on arr to get below output
Output should be 50

In [25]:
arr[4:,4][0]

50

#### 6. Use indexing on arr to get below output
      [[27],
       [32],
       [37]]

In [26]:
arr[0:3,1:2]

array([[27],
       [32],
       [37]])

#### 7. Use indexing on arr to get below output
      [46, 47, 48, 49, 50]

In [27]:
arr[-1]

array([46, 47, 48, 49, 50])

#### 8. Use indexing on arr to get below output
     [[41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50]]

In [28]:
arr[3:]

array([[41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50]])

### NumPy  Stats Functions

Use below given array 'arr'

In [29]:
arr = np.arange(10,40).reshape(6,5)
arr

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39]])

#### 9. Find the sum of all the values in given array 'arr'

In [30]:
np.sum(arr)

735

#### 10. Find the standard deviation of the values in given array 'arr'

In [31]:
np.std(arr)

8.65544144839919

#### 11.  Find the mean of all the values in given array 'arr'

In [32]:
np.mean(arr)

24.5

# Section 2: Pandas Solutions

In [33]:
import numpy as np
import pandas as pd

In [34]:
df = pd.read_csv("Stores Sales.csv")

### Q1. Display the first 10 entries of the dataset.

In [35]:
df.head(10)

Observation  Dist_Taxi  Dist_Market  Dist_Metro  Store_Area  \
0            1     9796.0       5250.0     10703.0      1659.0   
1            2     8294.0       8186.0     12694.0      1461.0   
2            3    11001.0      14399.0     16991.0      1340.0   
3            4     8301.0      11188.0     12289.0      1451.0   
4            5    10510.0      12629.0     13921.0      1770.0   
5            6     6665.0       5142.0      9972.0      1442.0   
6            7    13153.0      11869.0     17811.0      1542.0   
7            8     5882.0       9948.0     13315.0      1261.0   
8            9     7495.0      11589.0     13370.0      1090.0   
9           10     8233.0       7067.0     11400.0      1030.0   

   Items_Available       Parking Coupon_Category  Daily_Customer_Count  \
0           1961.0          Open           CAT B                   530   
1           1752.0  Not Provided           CAT B                   210   
2           1609.0  Not Provided           CAT A                   720   
3           1748.0       Covered           CAT B                   620   
4           2111.0  Not Provided           CAT B                   450   
5           1733.0          Open           CAT B                   760   
6           1858.0    No Parking           CAT A                  1030   
7           1507.0          Open           CAT C                  1020   
8           1321.0  Not Provided           CAT B                   680   
9           1235.0          Open           CAT C                  1130   

   Store_Sales  
0        66490  
1        39820  
2        54010  
3        53730  
4        46620  
5        45260  
6        72240  
7        37720  
8        46310  
9        44150

### Q2. Display the last 5 entries of the dataset.

In [36]:
df.tail()

Observation  Dist_Taxi  Dist_Market  Dist_Metro  Store_Area  \
927          928    12176.0       8518.0     15673.0      1582.0   
928          929     7214.0       8717.0     10553.0      1387.0   
929          930     7423.0      11708.0     13220.0      1200.0   
930          931    15082.0      14700.0     19617.0      1299.0   
931          932     9297.0      12537.0     14418.0      1174.0   

     Items_Available  Parking Coupon_Category  Daily_Customer_Count  \
927           1910.0  Covered           CAT C                  1080   
928           1663.0     Open           CAT A                   850   
929           1436.0     Open           CAT A                  1060   
930           1560.0     Open           CAT B                   770   
931           1429.0  Covered           CAT C                  1110   

     Store_Sales  
927        66390  
928        82080  
929        76440  
930        96610  
931        54340

### Q3. How many rows and columns are present in the dataset?

In [37]:
a = df.shape
print("There are",a[0],"rows and",a[1],"columns.")

There are 932 rows and 10 columns.


### Q4. What are the different data types of the variables in the given dataset?

In [38]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 932 entries, 0 to 931
Data columns (total 10 columns):
Observation             932 non-null int64
Dist_Taxi               919 non-null float64
Dist_Market             919 non-null float64
Dist_Metro              931 non-null float64
Store_Area              924 non-null float64
Items_Available         917 non-null float64
Parking                 932 non-null object
Coupon_Category         932 non-null object
Daily_Customer_Count    932 non-null int64
Store_Sales             932 non-null int64
dtypes: float64(5), int64(3), object(2)
memory usage: 72.9+ KB


**Or you can use below command as well**

In [39]:
df.get_dtype_counts()

C:\Users\IT\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: `get_dtype_counts` has been deprecated and will be removed in a future version. For DataFrames use `.dtypes.value_counts()
  """Entry point for launching an IPython kernel.


float64    5
int64      3
object     2
dtype: int64

### Q5. Print all the values of the variable 'Dist_Metro'.

In [40]:
print(df['Dist_Metro'])

0      10703.0
1      12694.0
2      16991.0
3      12289.0
4      13921.0
        ...   
927    15673.0
928    10553.0
929    13220.0
930    19617.0
931    14418.0
Name: Dist_Metro, Length: 932, dtype: float64


### Q6. Drop the variable 'Parking' from the dataset.

In [41]:
df_1 = df.drop('Parking',axis=1)     
df_1.head()

Observation  Dist_Taxi  Dist_Market  Dist_Metro  Store_Area  \
0            1     9796.0       5250.0     10703.0      1659.0   
1            2     8294.0       8186.0     12694.0      1461.0   
2            3    11001.0      14399.0     16991.0      1340.0   
3            4     8301.0      11188.0     12289.0      1451.0   
4            5    10510.0      12629.0     13921.0      1770.0   

   Items_Available Coupon_Category  Daily_Customer_Count  Store_Sales  
0           1961.0           CAT B                   530        66490  
1           1752.0           CAT B                   210        39820  
2           1609.0           CAT A                   720        54010  
3           1748.0           CAT B                   620        53730  
4           2111.0           CAT B                   450        46620

### Q7. Print 'True' for the observations of the 'Dist_Taxi' variable whose value is greater than 8229.
**Using dataframe from Q6**

In [42]:
print(df_1['Dist_Taxi']>8229)

0       True
1       True
2       True
3       True
4       True
       ...  
927     True
928    False
929    False
930     True
931     True
Name: Dist_Taxi, Length: 932, dtype: bool


### Q8. Drop the missing values ('na' values) from the dataset.

In [43]:
df_2 = df.dropna()

### Q9. Group the dataset with respect to the variable 'Dist_Market' using aggregation function min()
**Use dataframe originally loaded i.e Q1 dataset**

In [44]:
df.groupby("Dist_Market").min()

Observation  Dist_Taxi  Dist_Metro  Store_Area  Items_Available  \
Dist_Market                                                                    
1666.0               855      146.0      3227.0      1072.0           1296.0   
4402.0               424     4049.0      8614.0      1948.0           2374.0   
4574.0               767     5097.0      9365.0      1449.0           1733.0   
4644.0               867     6486.0      9312.0      1330.0           1606.0   
4950.0               585     1648.0      6583.0       932.0           1138.0   
...                  ...        ...         ...         ...              ...   
17541.0              437    12794.0     20046.0      1440.0           1733.0   
17552.0              358    11986.0     19014.0      1638.0           1952.0   
17958.0              903    11304.0     19046.0      1648.0           1959.0   
18281.0              339     9308.0     18532.0      1771.0           2147.0   
20945.0              361    20662.0     23294.0     24300.0          12730.0   

                  Parking Coupon_Category  Daily_Customer_Count  Store_Sales  
Dist_Market                                                                   
1666.0               Open           CAT C                   900        47590  
4402.0               Open           CAT A                   930        89540  
4574.0            Covered           CAT C                   320        60060  
4644.0            Covered           CAT C                   590        38510  
4950.0               Open           CAT B                   820        89760  
...                   ...             ...                   ...          ...  
17541.0        No Parking           CAT A                  1120        65310  
17552.0      Not Provided           CAT A                   690        81840  
17958.0        No Parking           CAT A                   370        77080  
18281.0              Open           CAT C                   430        62710  
20945.0           Covered           CAT B                  1130      1500000  

[866 rows x 9 columns]

### Q10. Export the Q6 dataframe without the 'Parking' column into a csv file.

In [45]:
df_1.to_csv('df.csv',index=False) 