# NumPy

numpy is python's package for doing math that is more advanced than +-*/

This includes special functions like cosine, exponential, sqrt, ...

On top of this we can use numpy to generate samples from many types of random variables

numpy also has a powerful data type to define vectors, matrices, and tensors

With these data types numpy also allows us to do linear algebra - matrix multiplication and matrix-vector solutions

In [1]:
# the first step of using numpy is to tell python to use it
import numpy as np

In [12]:
print(np.sin(np.pi))
# np.cos
print(np.pi)
print(np.sqrt(1.21))
print(np.exp(5.2))
print(np.log(np.exp(5.2)))
print(np.sqrt(np.exp(5.2)))
np.random.default_rng(222)

1.2246467991473532e-16
3.141592653589793
1.1
181.27224187515122
5.2
13.463738035001692


Generator(PCG64) at 0x21108700048

In [13]:
# we can create numpy arrays by converting lists
# this is a vector
vec = np.array([1,2,3])
print(vec)
# we can create matrices by converting lists of lists
mat = np.array([[1,2,1],[4,5,9],[1,8,9]])
print('')
print(mat)
print('')
print(mat.T)

[1 2 3]

[[1 2 1]
 [4 5 9]
 [1 8 9]]

[[1 4 1]
 [2 5 8]
 [1 9 9]]


In [14]:
# there are lots of other ways to create numpy arrays
vec2 = np.arange(0,15)
print(vec2)
print('')
vec3 = np.arange(3,21,6)
print(vec3)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]

[ 3  9 15]


In [15]:

vec4 = np.linspace(0,5,10)
print(vec4)
print('')
print(vec4.reshape(5,2))
vec4_reshaped = vec4.reshape(5,2)
print(vec4_reshaped)
print(vec4)

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]

[[0.         0.55555556]
 [1.11111111 1.66666667]
 [2.22222222 2.77777778]
 [3.33333333 3.88888889]
 [4.44444444 5.        ]]
[[0.         0.55555556]
 [1.11111111 1.66666667]
 [2.22222222 2.77777778]
 [3.33333333 3.88888889]
 [4.44444444 5.        ]]
[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


In [ ]:
mat2 = np.zeros([5,3])
print(mat2)
mat3 = np.ones((3,5))
print('')
print(mat3)
mat4 = np.eye(5)
print('')
print(mat4)

In [16]:
# we can +-*/ arrays together if they're the right size
vec5 = np.arange(1,6)
vec6 = np.arange(3,8)
print(vec5)
print(vec6)
print(vec5+vec6)
print(vec5*vec6)
print(1/vec5)
print(np.sqrt(vec6))

[1 2 3 4 5]
[3 4 5 6 7]
[ 4  6  8 10 12]
[ 3  8 15 24 35]
[1.         0.5        0.33333333 0.25       0.2       ]
[1.73205081 2.         2.23606798 2.44948974 2.64575131]


In [17]:
# we can do matrix multiplication
print(mat)
print('')
print(vec)
print()
product = np.matmul(mat,vec)
print(product)

[[1 2 1]
 [4 5 9]
 [1 8 9]]

[1 2 3]

[ 8 41 44]


In [18]:
print(np.linalg.solve(mat,product))
print('')
print(np.linalg.inv(mat))

[1. 2. 3.]

[[ 0.5         0.18518519 -0.24074074]
 [ 0.5        -0.14814815  0.09259259]
 [-0.5         0.11111111  0.05555556]]


In [19]:
# we can find the unique values in an array
vec7 = np.array(['blue','red','orange','purple','purple','orange','Red',6])
print(vec7)
print(np.unique(vec7))

['blue' 'red' 'orange' 'purple' 'purple' 'orange' 'Red' '6']
['6' 'Red' 'blue' 'orange' 'purple' 'red']


In [20]:
# we can also use numpy to generate samples of a random variable
rand_mat = np.random.rand(5,5) # uniform random variable
print(rand_mat)
rand_mat2 = np.random.randn(10,5) # standard normal random variable
print('')
print(rand_mat2)

[[0.61744586 0.18122184 0.60966715 0.91365624 0.10568396]
 [0.51365019 0.2443462  0.95530232 0.49960178 0.96246691]
 [0.52641202 0.39251557 0.62343756 0.48534275 0.71398375]
 [0.46431969 0.86645077 0.42770083 0.76696982 0.70795776]
 [0.25747303 0.17253028 0.58549242 0.7618755  0.9677564 ]]

[[ 1.70566706  0.57211391  0.83527956  0.31168436  0.21611569]
 [ 0.13353359 -0.41664079 -0.91315263  1.22307725 -1.43301058]
 [ 0.74010181 -0.36853813 -0.42864059  0.00983069  0.20957799]
 [ 0.77557668 -1.77988888  1.62575069 -0.55287984  1.49807495]
 [ 0.30790242  0.47555602 -0.69109321 -0.06361602 -0.61321814]
 [-0.66980003  0.33595702  1.10153074 -0.32710196 -0.30436546]
 [-0.20146153  0.67201027  0.40937048  1.47879843 -0.52279615]
 [-0.77143157  1.06779053  0.49219953 -0.41958699 -0.46380803]
 [ 0.12386753 -0.57977248  0.56762825  2.34782869 -0.74631371]
 [ 0.93254388 -0.63967321  0.54252733 -1.48570265 -0.63954847]]


In [22]:
# we can also use numpy for statistical tools on arrays
print(np.mean(rand_mat))
print(np.std(rand_mat2))

0.572930425558127
0.865513959744913


In [23]:
print(np.min(rand_mat))
print(np.max(rand_mat2))

0.10568395723850221
2.347828692748773


In [ ]:
# break here for next video!

In [24]:
# how do we access entries in a numpy vector
rand_vec = np.random.randn(19)
print(rand_vec)
print(rand_vec[6])

[-1.59139735e+00  1.48048588e-01  1.41157823e+00 -3.82694740e-01
 -4.74842393e-01  1.13363368e-03  5.15207617e-01  1.25809537e+00
 -4.68289821e-02  2.54659931e-01 -9.27627585e-02 -2.38235517e-01
 -3.31820927e-02 -7.18692220e-02  4.70952369e-01 -1.45902891e-02
  6.12536297e-01 -2.39705746e-01  1.74835574e-01]
0.5152076170504933


In [25]:
# we can access multiple entries at once using :
print(rand_vec[4:9])

[-4.74842393e-01  1.13363368e-03  5.15207617e-01  1.25809537e+00
 -4.68289821e-02]


In [26]:
# we can also access multiple non-consecutive entries using np.arange
print(np.arange(0,15,3))
print(rand_vec[np.arange(0,15,3)])

[ 0  3  6  9 12]
[-1.59139735 -0.38269474  0.51520762  0.25465993 -0.03318209]


In [27]:
# what about matrices
print(rand_mat)
print(rand_mat[1][2])
print(rand_mat[1,2])


[[0.61744586 0.18122184 0.60966715 0.91365624 0.10568396]
 [0.51365019 0.2443462  0.95530232 0.49960178 0.96246691]
 [0.52641202 0.39251557 0.62343756 0.48534275 0.71398375]
 [0.46431969 0.86645077 0.42770083 0.76696982 0.70795776]
 [0.25747303 0.17253028 0.58549242 0.7618755  0.9677564 ]]
0.9553023249563669
0.9553023249563669


In [28]:
print(rand_mat[0:2,1:3])

[[0.18122184 0.60966715]
 [0.2443462  0.95530232]]


In [29]:
# let's change some values in an array!
print(rand_vec)
rand_vec[3:5] = 4
print('')
print(rand_vec)
rand_vec[3:5] = [1,2]
print('')
print(rand_vec)

[-1.59139735e+00  1.48048588e-01  1.41157823e+00 -3.82694740e-01
 -4.74842393e-01  1.13363368e-03  5.15207617e-01  1.25809537e+00
 -4.68289821e-02  2.54659931e-01 -9.27627585e-02 -2.38235517e-01
 -3.31820927e-02 -7.18692220e-02  4.70952369e-01 -1.45902891e-02
  6.12536297e-01 -2.39705746e-01  1.74835574e-01]

[-1.59139735e+00  1.48048588e-01  1.41157823e+00  4.00000000e+00
  4.00000000e+00  1.13363368e-03  5.15207617e-01  1.25809537e+00
 -4.68289821e-02  2.54659931e-01 -9.27627585e-02 -2.38235517e-01
 -3.31820927e-02 -7.18692220e-02  4.70952369e-01 -1.45902891e-02
  6.12536297e-01 -2.39705746e-01  1.74835574e-01]

[-1.59139735e+00  1.48048588e-01  1.41157823e+00  1.00000000e+00
  2.00000000e+00  1.13363368e-03  5.15207617e-01  1.25809537e+00
 -4.68289821e-02  2.54659931e-01 -9.27627585e-02 -2.38235517e-01
 -3.31820927e-02 -7.18692220e-02  4.70952369e-01 -1.45902891e-02
  6.12536297e-01 -2.39705746e-01  1.74835574e-01]


In [30]:
print(rand_mat)
rand_mat[1:3,3:5] = 0
print('')
print(rand_mat)

[[0.61744586 0.18122184 0.60966715 0.91365624 0.10568396]
 [0.51365019 0.2443462  0.95530232 0.49960178 0.96246691]
 [0.52641202 0.39251557 0.62343756 0.48534275 0.71398375]
 [0.46431969 0.86645077 0.42770083 0.76696982 0.70795776]
 [0.25747303 0.17253028 0.58549242 0.7618755  0.9677564 ]]

[[0.61744586 0.18122184 0.60966715 0.91365624 0.10568396]
 [0.51365019 0.2443462  0.95530232 0.         0.        ]
 [0.52641202 0.39251557 0.62343756 0.         0.        ]
 [0.46431969 0.86645077 0.42770083 0.76696982 0.70795776]
 [0.25747303 0.17253028 0.58549242 0.7618755  0.9677564 ]]


In [31]:
sub_mat = rand_mat[0:2,0:3]
print(sub_mat)
sub_mat[:] = 3
print(sub_mat)


[[0.61744586 0.18122184 0.60966715]
 [0.51365019 0.2443462  0.95530232]]
[[3. 3. 3.]
 [3. 3. 3.]]


In [32]:
print(rand_mat)

[[3.         3.         3.         0.91365624 0.10568396]
 [3.         3.         3.         0.         0.        ]
 [0.52641202 0.39251557 0.62343756 0.         0.        ]
 [0.46431969 0.86645077 0.42770083 0.76696982 0.70795776]
 [0.25747303 0.17253028 0.58549242 0.7618755  0.9677564 ]]


In [33]:
sub_mat2 = rand_mat[0:2,0:3].copy()
sub_mat2[:] = 99
print(sub_mat2)
print(rand_mat)


[[99. 99. 99.]
 [99. 99. 99.]]
[[3.         3.         3.         0.91365624 0.10568396]
 [3.         3.         3.         0.         0.        ]
 [0.52641202 0.39251557 0.62343756 0.         0.        ]
 [0.46431969 0.86645077 0.42770083 0.76696982 0.70795776]
 [0.25747303 0.17253028 0.58549242 0.7618755  0.9677564 ]]


In [ ]:
# break here for next video

In [34]:
# we can also access entries with logicals
rand_vec = np.random.randn(15)

print(rand_vec)
print(rand_vec>0)
print(rand_vec[rand_vec>0])

[ 0.57859293  1.15694496  0.0558618  -0.29413361 -1.43873521 -0.11072101
 -1.8672516   0.17632939 -0.22899149 -1.10786136 -0.53310949  1.82169176
 -0.6741655  -1.47402142 -0.20667006]
[ True  True  True False False False False  True False False False  True
 False False False]
[0.57859293 1.15694496 0.0558618  0.17632939 1.82169176]


In [36]:
print(rand_mat2)
print(rand_mat2[rand_mat2>0])

[[ 1.70566706  0.57211391  0.83527956  0.31168436  0.21611569]
 [ 0.13353359 -0.41664079 -0.91315263  1.22307725 -1.43301058]
 [ 0.74010181 -0.36853813 -0.42864059  0.00983069  0.20957799]
 [ 0.77557668 -1.77988888  1.62575069 -0.55287984  1.49807495]
 [ 0.30790242  0.47555602 -0.69109321 -0.06361602 -0.61321814]
 [-0.66980003  0.33595702  1.10153074 -0.32710196 -0.30436546]
 [-0.20146153  0.67201027  0.40937048  1.47879843 -0.52279615]
 [-0.77143157  1.06779053  0.49219953 -0.41958699 -0.46380803]
 [ 0.12386753 -0.57977248  0.56762825  2.34782869 -0.74631371]
 [ 0.93254388 -0.63967321  0.54252733 -1.48570265 -0.63954847]]
[1.70566706 0.57211391 0.83527956 0.31168436 0.21611569 0.13353359
 1.22307725 0.74010181 0.00983069 0.20957799 0.77557668 1.62575069
 1.49807495 0.30790242 0.47555602 0.33595702 1.10153074 0.67201027
 0.40937048 1.47879843 1.06779053 0.49219953 0.12386753 0.56762825
 2.34782869 0.93254388 0.54252733]


In [37]:

print(rand_vec)
print('')
rand_vec[rand_vec>0.5] = -5
print(rand_vec)

[ 0.57859293  1.15694496  0.0558618  -0.29413361 -1.43873521 -0.11072101
 -1.8672516   0.17632939 -0.22899149 -1.10786136 -0.53310949  1.82169176
 -0.6741655  -1.47402142 -0.20667006]

[-5.         -5.          0.0558618  -0.29413361 -1.43873521 -0.11072101
 -1.8672516   0.17632939 -0.22899149 -1.10786136 -0.53310949 -5.
 -0.6741655  -1.47402142 -0.20667006]


In [38]:
# let's save some arrays on the disk for use later!
np.save('saved_file_name',rand_mat2)


In [39]:
np.savez('zipped_file_name',rand_mat=rand_mat,rand_mat2=rand_mat2)

In [41]:
# now let's load it
loaded_vec = np.load('saved_file_name.npy')
loaded_zip = np.load('zipped_file_name.npz')

print(loaded_vec)
print('')
print(loaded_zip)

[[ 1.70566706  0.57211391  0.83527956  0.31168436  0.21611569]
 [ 0.13353359 -0.41664079 -0.91315263  1.22307725 -1.43301058]
 [ 0.74010181 -0.36853813 -0.42864059  0.00983069  0.20957799]
 [ 0.77557668 -1.77988888  1.62575069 -0.55287984  1.49807495]
 [ 0.30790242  0.47555602 -0.69109321 -0.06361602 -0.61321814]
 [-0.66980003  0.33595702  1.10153074 -0.32710196 -0.30436546]
 [-0.20146153  0.67201027  0.40937048  1.47879843 -0.52279615]
 [-0.77143157  1.06779053  0.49219953 -0.41958699 -0.46380803]
 [ 0.12386753 -0.57977248  0.56762825  2.34782869 -0.74631371]
 [ 0.93254388 -0.63967321  0.54252733 -1.48570265 -0.63954847]]



In [ ]:
print(loaded_zip['rand_mat'])
print('')
print(loaded_zip['rand_mat2'])

new_array  = loaded_zip['rand_mat']
print(new_array)

In [42]:
# we can also save/load as text files...but only single variables
np.savetxt('text_file_name.txt',rand_mat,delimiter=',')
rand_mat_txt = np.loadtxt('text_file_name.txt',delimiter=',')
print(rand_mat)
print('')
print(rand_mat_txt)

[[3.         3.         3.         0.91365624 0.10568396]
 [3.         3.         3.         0.         0.        ]
 [0.52641202 0.39251557 0.62343756 0.         0.        ]
 [0.46431969 0.86645077 0.42770083 0.76696982 0.70795776]
 [0.25747303 0.17253028 0.58549242 0.7618755  0.9677564 ]]

[[3.         3.         3.         0.91365624 0.10568396]
 [3.         3.         3.         0.         0.        ]
 [0.52641202 0.39251557 0.62343756 0.         0.        ]
 [0.46431969 0.86645077 0.42770083 0.76696982 0.70795776]
 [0.25747303 0.17253028 0.58549242 0.7618755  0.9677564 ]]
